version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
    volumes:
      - "C:\\Users\\pepe\\Desktop\\DataBase:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - "C:\\Users\\pepe\\Desktop\\pg:/var/lib/pgadmin"
    depends_on:
      - db